### ISSUE TITLE
Cannot remember output folder

### ISSUE THREAD

**Issue by LeonCheung** [jendabek/BlenderRenderController#10]
First, a holy time saver, thank you so much Jan!
Just tested, so far so good except that I have to re-set the output folder after reloading blend. Is that normal?

**Comment by LeonCheung** [comment]
Oops, just noticed it reads from the blend file. Hmm.

**Comment by jendabek** [comment]
Hi and thanks :) We can save an output folder that has been set in the tool for each .blend but I think it would become confusing. What do you think?

**Comment by LeonCheung** [comment]
Well, imho, it might be also confusing that ppl (like me here) don't even sure about that when using it by the first time, since we got both From Blend and Custom for Section 2 and 3.

**Comment by jendabek** [comment]
OK, we will add Custom option to that field.
