### ISSUE TITLE
[Feature Request] Display Percentage for Progress

### ISSUE THREAD

**Issue by LeonCheung** [jendabek/BlenderRenderController#11]
Showing percentage (or even ETA?) would be nice to manage the time better. (e.g. to know better how long it would take for a snacking time  :P  ) Thanks!

**Comment by jendabek** [comment]
Yep, working on it now :)

**Comment by jendabek** [comment]
Hello, can you please test this release with added ETA?
It is quite rough but it should give an idea if you are going to wait 1 minute or 1 hour 😄 
Just replace the exe with the one from the zip.

[BlenderRenderController_ETA.zip](https://github.com/jendabek/BlenderRenderController/files/853378/BlenderRenderController_ETA.zip)

**Comment by LeonCheung** [comment]
Haha, you got the point! One error message popped up and I don't know why:

![error](https://cloud.githubusercontent.com/assets/494788/24082966/5074dc28-0d09-11e7-9450-91b7b956043d.png)

Do you want me to paste the whole texts here?

**Comment by jendabek** [comment]
Hmm, can you please test this?
Please replace also the scripts folder.
[BlenderRenderController_ETA2.zip](https://github.com/jendabek/BlenderRenderController/files/853391/BlenderRenderController_ETA2.zip)

**Comment by jendabek** [comment]
You have a dual hexa-core system? :)

**Comment by LeonCheung** [comment]
Aha, you got me. :D Yeah. Dual XEON E5-2667,( which makes me an ideal tester for you? :D)

And, it works!
![test2](https://cloud.githubusercontent.com/assets/494788/24083153/5446b7aa-0d0d-11e7-8e12-510156725fb7.png)

Actually, I think the ETA can be referable enough after running for around one minute, which is much better than nothing. Thanks a lot!

And a little question: just wonder why the Render Mixdown and Join Chunks got no time-related information.

**Comment by LeonCheung** [comment]
Yeah! For simple tests so far, it gives a 8-10X speed-up, because it can make FULL use of the threads. So, cheers to you guys!

**Comment by jendabek** [comment]
The last version for today if you like to test it - I have added a progress bar in Windows TaskBar and to app title.
[BlenderRenderController_progress.zip](https://github.com/jendabek/BlenderRenderController/files/853422/BlenderRenderController_progress.zip)

**Comment by LeonCheung** [comment]
Cool enough!
![progress](https://cloud.githubusercontent.com/assets/494788/24087156/6139c83c-0d56-11e7-8387-04ba45b5d0cd.png)
