### ISSUE TITLE
Error occurs on Win7

### ISSUE THREAD

**Issue by LeonCheung** [jendabek/BlenderRenderController#12]
When trying to run it on my Win7 64bit workstation, error occurs:

![222](https://cloud.githubusercontent.com/assets/494788/24088479/cbfe0ade-0d65-11e7-9c3f-16189aa4f1aa.PNG)
Any advice please?

----
UPDATE: At least four other guys here failed to make it working on Win7.

**Comment by jendabek** [comment]
Will have to test it on Win7 - thanks for the report!
Can I ask you if the error happens everytime it is trying to load .blend?

**Comment by LeonCheung** [comment]
Yes. It does. And when I tried to temporally remove the MSVCR120.dll file from BL directory, BCR just kept on reading the file endlessly. So I bet there might be something related to it.

**Comment by jendabek** [comment]
OK, we will look at it, thanks!

**Comment by jendabek** [comment]
Hello, can you please run the program from Command Line on Windows 7 and let me know if it helps?
Then I will be sure the problem is there...

Thanks!

**Comment by LeonCheung** [comment]
Ah, it works by running from command line.  :)

**Comment by LeonCheung** [comment]
@jendabek So why it can work in this way and cannot in THAT way?

**Comment by jendabek** [comment]
We are trying to fix it at the moment, it looks like some strange security issue, I will let you know when we solve this. Thanks for the patience :)

**Comment by LeonCheung** [comment]
Cool and thank you!
