### ISSUE TITLE
loadblend() standardError plugin conflict

### ISSUE THREAD

**Issue by RedRaptor93** [jendabek/BlenderRenderController#15]
I use a couple of plugins in VSE and I went to test BRC today and this started to happend:

![image](https://cloud.githubusercontent.com/assets/25366969/24205814/35806baa-0efb-11e7-9b79-cc2d0dee1e4d.png)

This stops the program from reading the .blend info, however, these errors are **harmless** to the rest of the program! All the info gets read and rendering works if I remove the bit of code that says otherwise. 

I don't think it's necessary to check _StandardError_ in this situation, let alone stop the entire process.

**Comment by jendabek** [comment]
The more important issue is that it doesn't read the .blend on Win7, it runs fine only when running BRC from Command Promp. Do you have any idea?

**Comment by jendabek** [comment]
![2017-03-22_170847](https://cloud.githubusercontent.com/assets/3582231/24207845/45938f5a-0f22-11e7-87fc-c6922ce7482e.jpg)

**Comment by RedRaptor93** [comment]
It might be a encoding issue from a quick google search, try converting the encoding to UTF-8 in Win7, change the line ends too for good measure.



I was unaware of this problem, but please, next time point to another issue topic to discuss instead of changing the subject ok 😉 I wanted your opinion on the issue I found.

**Comment by jendabek** [comment]
OK, sorry. Thats an error caused by some plugin and it has nothing to do with loading .blend data so a blend should be still readed fine. I have set it to stop on every error because of that issue with loading blends on Win 7, I will remove it when find a solution.
Unfortunately, changing encoding didn't make any change :-/

**Comment by RedRaptor93** [comment]
I can't find much about that error, might be worth asking for help in StackOverflow. I'll install a Win7 VM to troubleshoot this too.
