### ISSUE TITLE
Win7 issue discussion

### ISSUE THREAD

**Issue by RedRaptor93** [jendabek/BlenderRenderController#16]
As of this post, BRC has problems opening projects in Win7. It's some sort of Python issue as far as I know

Fixing this is a priority!

Until that happens, a workaround is to launch _BlenderRenderController.exe_ by the command line

**Comment by jendabek** [comment]
I have just noticed that Blender crashes when the process is called so python cannot be processed.

**Comment by RedRaptor93** [comment]
Found another problem, I called BRC by the console to test if rendering would still work.

It did render chunks and mixdown like it should, but when came the time to join them, it got stuck on a loop where it the "Please select FFmpeg path" message popping up every few seconds.

![loopbrc](https://cloud.githubusercontent.com/assets/25366969/24214928/d4656896-0f15-11e7-916b-c171ce18b701.png)


however, the files were fine, it got messed up when calling ffmpeg to join them

**Comment by RedRaptor93** [comment]
have you tried debugging in Win7?

**Comment by RedRaptor93** [comment]
there seems to be a pattern here: I have problems _**calling**_ ffmpeg and you have a problem _**calling**_ blender..

maybe it's some oddity about starting processes in Win7?

**Comment by jendabek** [comment]
are you trying that on 64-bit or 32-bit Win7?

**Comment by jendabek** [comment]
It may be some security issue... calling notepad.exe works.

**Comment by RedRaptor93** [comment]
I'm using Win7pro 32bit

**Comment by jendabek** [comment]
Me too... still cant figure it out :-/

**Comment by RedRaptor93** [comment]
figured out my FFmpeg problem... I was using the 64bit FFmpeg on my 32bit system, whoops 🙄 

So launching BRC from CMD does work,

 still not sure about the Python issue... I installed VS on my VM and that doesn't show during debugging

**Comment by RedRaptor93** [comment]
I tweaked the error detection when reading _.blend_ info. Now it will only halt the operation and show a error if the get info process fails (StandardOutput = null). So Errors that don't interfere w/ that (like those plugin errors I've got) won't stop it.

Sadly, still have no idea what causes that Win7 problem... Have you tried asking around stackoverflow.com or some site like that?

**Comment by RedRaptor93** [comment]
IT'S IS A UAC SECURITY PROBLEM, turning off UAC makes it all work.

**Comment by jendabek** [comment]
Yep, but running the app as an Administrator does not make any change. Do you have any idea?

**Comment by RedRaptor93** [comment]
I think the issue is the EXTERNAL processes we call (to get the .blend info for instance) don't get the necessary privilegies. 

I guess due to some Win7 issue they don't execute using the privilegies from the caller or the user, so even running as administrador won't work.

**Comment by jendabek** [comment]
I have tried to disable UAC in Win7 by setting that slider to "Never notify" and it still doesn't work... Are you sure that this made a change?

**Comment by RedRaptor93** [comment]
Crap, I though I got it working, but i tested again and it didn't 💀 💀 

Still, I believe the most likely cause is UAC.

**Comment by RedRaptor93** [comment]
I made a _.bat_ file to test _get_project_info.py_ outside the program. It works in Windows 10, but only works in Windows 7 by running as administrator.

**Comment by jendabek** [comment]
[runWin7.zip](https://github.com/jendabek/BlenderRenderController/files/870348/runWin7.zip)
Maybe we could add this batch file to release zip until we figure it out?

**Comment by RedRaptor93** [comment]
yea, for now that's the best thing to do. Later we can figure out a better to make these calls work.

**Comment by jendabek** [comment]
I will try to figure it out tommorow when I meet my friend - an excellent programmer :)

**Comment by lpslp** [comment]
for me it not working 
win 7 x64 
when run just BRC ![bb](https://cloud.githubusercontent.com/assets/19380636/24336036/d281aa46-1288-11e7-8b7a-780530115e9d.jpg)

when run just your runWin7.zip 
![bb1](https://cloud.githubusercontent.com/assets/19380636/24336042/dc9b95aa-1288-11e7-9f92-1f09b7213990.jpg)

**Comment by RedRaptor93** [comment]
@lpslp Can you send the full message from the runWin7 error? Translated if possible?

**Comment by lpslp** [comment]
pic 1 error

> Сигнатура проблемы:
>   Имя события проблемы:	APPCRASH
>   Имя приложения:	blender.exe
>   Версия приложения:	2.7.8.0
>   Отметка времени приложения:	58d9cda2
>   Имя модуля с ошибкой:	MSVCR120.dll
>   Версия модуля с ошибкой:	12.0.21005.1
>   Отметка времени модуля с ошибкой:	524f83ff
>   Код исключения:	40000015
>   Смещение исключения:	0000000000074a46
>   Версия ОС:	6.1.7601.2.1.0.256.1
>   Код языка:	1049
>   Дополнительные сведения 1:	8f27
>   Дополнительные сведения 2:	8f273a46949532b247124c19dd9bfc51
>   Дополнительные сведения 3:	7323
>   Дополнительные сведения 4:	7323d7da9e47cae863227c78d79cc1a9
> 
> Ознакомьтесь с заявлением о конфиденциальности в Интернете:
>   http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0419
> 
> Если заявление о конфиденциальности в Интернете недоступно, ознакомьтесь с его локальным вариантом:
>   C:\Windows\system32\ru-RU\erofflps.txt


pic 2 error
```
Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в BlenderRenderController.Helper.fixPath(String path)
   в BlenderRenderController.MainForm.loadBlend()
   в BlenderRenderController.MainForm.blendFileBrowseButton_Click(Object sender, EventArgs e)
   в System.Windows.Forms.Control.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ButtonBase.WndProc(Message& m)
   в System.Windows.Forms.Button.WndProc(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BlenderRenderController
    Версия сборки: 0.8.0.0
    Версия Win32: 0.8.0.0
    CodeBase: file:///D:/3d/blender_scripts/Tool%20for%20VSE%20multithreaded%20rendering%20(min.%203x%20faster)/BRE-0.8.0-Full/BlenderRenderController.exe
----------------------------------------
System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Web.Extensions
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.17929
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Web
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Оперативная отладка (JIT) **************
Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.

Например:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

При включенной отладке JIT любое необрабатываемое исключение
пересылается отладчику JIT, зарегистрированному на данном компьютере,
вместо того чтобы обрабатываться данным диалоговым окном.



```

**Comment by RedRaptor93** [comment]
@lpslp thank you, btw is there a _log.txt_ in the exe folder? If so send it too.

**Comment by lpslp** [comment]
> btw is there a log.txt in the exe folder
no. program just freeze after press "close"

**Comment by RedRaptor93** [comment]
@lpslp could you try to run this _.bat_? Post the results here

[getInfoTest.zip](https://github.com/jendabek/BlenderRenderController/files/883309/getInfoTest.zip)

In cmd:
> getInfoTest.bat "path/to/Blender.exe" "path/to/.blend"

**Comment by lpslp** [comment]
p.s. i probably know what you do say about my log but - take in mind - all my projects works and rendering inside blender it self - fine

`Read prefs: C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.78\co
nfig\userpref.blend
AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead
found bundled python: D:\3d\Blender 2.78\2.78\python
Imported multifiles
Exception in module register(): 'C:\\Users\\xxxX6\\AppData\\Roaming\\Blender
Foundation\\Blender\\2.78\\scripts\\addons\\brush_quickset.py'
Traceback (most recent call last):
  File "D:\3d\Blender 2.78\2.78\scripts\modules\addon_utils.py", line 350, in en
able
    mod.register()
  File "C:\Users\xxxX6\AppData\Roaming\Blender Foundation\Blender\2.78\script
s\addons\brush_quickset.py", line 452, in register
    if not cfg.keymaps.__contains__('Sculpt'):
AttributeError: 'NoneType' object has no attribute 'keymaps'
Exception in module register(): 'C:\\Users\\xxxX6\\AppData\\Roaming\\Blender
Foundation\\Blender\\2.78\\scripts\\addons\\rotation_constrained.py'
Traceback (most recent call last):
  File "D:\3d\Blender 2.78\2.78\scripts\modules\addon_utils.py", line 350, in en
able
    mod.register()
  File "C:\Users\xxxX6\AppData\Roaming\Blender Foundation\Blender\2.78\script
s\addons\rotation_constrained.py", line 101, in register
    km = wm.keyconfigs.addon.keymaps.new(name='Mesh', space_type='EMPTY')
AttributeError: 'NoneType' object has no attribute 'keymaps'
addon not found: 'vb30'
Exception in module register(): 'C:\\Users\\xxxX6\\AppData\\Roaming\\Blender
Foundation\\Blender\\2.78\\scripts\\addons\\1D_Scripts.py'
Traceback (most recent call last):
  File "D:\3d\Blender 2.78\2.78\scripts\modules\addon_utils.py", line 350, in en
able
    mod.register()
  File "C:\Users\xxxX6\AppData\Roaming\Blender Foundation\Blender\2.78\script
s\addons\1D_Scripts.py", line 5866, in register
    km = wm.keyconfigs.addon.keymaps.new(name='offset', space_type='VIEW_3D')
AttributeError: 'NoneType' object has no attribute 'keymaps'
Exception in module register(): 'C:\\Users\\xxxX6\\AppData\\Roaming\\Blender
Foundation\\Blender\\2.78\\scripts\\addons\\HOps\\__init__.py'
Traceback (most recent call last):
  File "D:\3d\Blender 2.78\2.78\scripts\modules\addon_utils.py", line 350, in en
able
    mod.register()
  File "C:\Users\xxxX6\AppData\Roaming\Blender Foundation\Blender\2.78\script
s\addons\HOps\__init__.py", line 41, in register
    register_all()
  File "C:\Users\xxxX6\AppData\Roaming\Blender Foundation\Blender\2.78\script
s\addons\HOps\registration.py", line 13, in register_all
    register_keymap()
  File "C:\Users\xxxX6\AppData\Roaming\Blender Foundation\Blender\2.78\script
s\addons\HOps\keymap.py", line 7, in register_keymap
    km = addon.keymaps.new(name = "3D View", space_type = "VIEW_3D")
AttributeError: 'NoneType' object has no attribute 'keymaps'
Exception in module register(): 'D:\\3d\\Blender 2.78\\2.78\\scripts\\addons\\ob
ject_boolean_tools.py'
Traceback (most recent call last):
  File "D:\3d\Blender 2.78\2.78\scripts\modules\addon_utils.py", line 350, in en
able
    mod.register()
  File "D:\3d\Blender 2.78\2.78\scripts\addons\object_boolean_tools.py", line 13
96, in register
    km = wm.keyconfigs.addon.keymaps.new(name='Object Mode')
AttributeError: 'NoneType' object has no attribute 'keymaps'
Exception in module register(): 'C:\\Users\\xxxX6\\AppData\\Roaming\\Blender
Foundation\\Blender\\2.78\\scripts\\addons\\retopoflow-master\\__init__.py'
Traceback (most recent call last):
  File "D:\3d\Blender 2.78\2.78\scripts\modules\addon_utils.py", line 350, in en
able
    mod.register()
  File "C:\Users\xxxX6\AppData\Roaming\Blender Foundation\Blender\2.78\script
s\addons\retopoflow-master\__init__.py", line 93, in register
    km = kc.keymaps.new(name='3D View', space_type='VIEW_3D')
AttributeError: 'NoneType' object has no attribute 'keymaps'
Exception in module register(): 'C:\\Users\\xxxX6\\AppData\\Roaming\\Blender
Foundation\\Blender\\2.78\\scripts\\addons\\VSE_Transform_Tool.py'
Traceback (most recent call last):
  File "D:\3d\Blender 2.78\2.78\scripts\modules\addon_utils.py", line 350, in en
able
    mod.register()
  File "C:\Users\xxxX6\AppData\Roaming\Blender Foundation\Blender\2.78\script
s\addons\VSE_Transform_Tool.py", line 1515, in register
    km = bpy.context.window_manager.keyconfigs.default.keymaps['View2D']
AttributeError: 'NoneType' object has no attribute 'keymaps'
--------------------------------------------
Corona: Bitbucket version 4.1.0
Corona: Starting add-on, version 3.1.11
Adding UI Panel: Corona render settings
Adding UI Panel: camera
Adding UI Panel: material
Adding UI Panel: environment
Adding UI Panel: particle systems
Adding UI Panel: Corona render passes
Adding UI Panel: Corona object properties
Adding UI Panel: lamp
Corona: Add-on started
--------------------------------------------
Registered SpeedSculpt with 11 modules
Exception in module register(): 'C:\\Users\\xxxX6\\AppData\\Roaming\\Blender
Foundation\\Blender\\2.78\\scripts\\addons\\BoxCutter\\__init__.py'
Traceback (most recent call last):
  File "D:\3d\Blender 2.78\2.78\scripts\modules\addon_utils.py", line 350, in en
able
    mod.register()
  File "C:\Users\xxxX6\AppData\Roaming\Blender Foundation\Blender\2.78\script
s\addons\BoxCutter\__init__.py", line 72, in register
    km = kc.keymaps.new(name='3D View', space_type='VIEW_3D')
AttributeError: 'NoneType' object has no attribute 'keymaps'
Exception in module register(): 'C:\\Users\\xxxX6\\AppData\\Roaming\\Blender
Foundation\\Blender\\2.78\\scripts\\addons\\asset_management_V_2_1_3\\__init__.p
y'
Traceback (most recent call last):
  File "D:\3d\Blender 2.78\2.78\scripts\modules\addon_utils.py", line 350, in en
able
    mod.register()
  File "C:\Users\xxxX6\AppData\Roaming\Blender Foundation\Blender\2.78\script
s\addons\asset_management_V_2_1_3\__init__.py", line 656, in register
    register_keymaps()
  File "C:\Users\xxxX6\AppData\Roaming\Blender Foundation\Blender\2.78\script
s\addons\asset_management_V_2_1_3\__init__.py", line 632, in register_keymaps
    km = wm.keyconfigs.addon.keymaps.new(name = "3D View", space_type = "VIEW_3D
")
AttributeError: 'NoneType' object has no attribute 'keymaps'
search for unknown operator 'BTOOL_OT_boolean_inters_direct', 'BTOOL_OT_boolean_
inters_direct'
search for unknown operator 'BTOOL_OT_boolean_diff_direct', 'BTOOL_OT_boolean_di
ff_direct'
search for unknown operator 'BTOOL_OT_boolean_union_direct', 'BTOOL_OT_boolean_u
nion_direct'
search for unknown operator 'MESH_OT_push_pull_face', 'MESH_OT_push_pull_face'
Warning: TypeError('bpy_struct: item.attr = val: enum "ROLLLEFT" not found in (\
'ANGLE\', \'LEFT\', \'RIGHT\')',)
Warning: TypeError('bpy_struct: item.attr = val: enum "ROLLTRIGHT" not found in
(\'ANGLE\', \'LEFT\', \'RIGHT\')',)
Warning: TypeError('bpy_struct: item.attr = val: enum "ROLLLEFT" not found in (\
'ANGLE\', \'LEFT\', \'RIGHT\')',)
Warning: TypeError('bpy_struct: item.attr = val: enum "ROLLTRIGHT" not found in
(\'ANGLE\', \'LEFT\', \'RIGHT\')',)
Read blend: D:\work\blender\sergey-2\war_story.blend
Info: Read library:  'D:\work\blender\sergey-2\B_S_comp.blend', 'D:\work\blender
\sergey-2\B_S_comp.blend', parent '<direct>'
Info: Read library:  'D:\work\blender\sergey-2\like.blend', 'D:\work\blender\ser
gey-2\like.blend', parent '<direct>'
Warning: Unable to open 'D:\work\blender\sergey-2\like.blend': No such file or d
irectory
Warning: Cannot find lib 'D:\work\blender\sergey-2\like.blend'
Warning: LIB: MovieClip: '0001.png' missing from 'D:\work\blender\sergey-2\like.
blend', parent '<direct>'
{
    "end": 43772,
    "fps": 3,
    "fpsBase": 0.10010000318288803,
    "outputPath": "E:\\",
    "projectName": "war_story",
    "renderFormat": "FFMPEG",
    "resolution": "1920 x 1080",
    "resolutionPercentage": 100,
    "sceneActive": "Scene",
    "scenesNum": "7",
    "start": 1
}

Blender quit

D:\3d\blender_scripts\Tool for VSE multithreaded rendering (min. 3x faster)\BRE-
0.8.0-Full\scripts>getInfoTest.bat "D:\3d\Blender 2.78\Blender.exe" "D:\work\ble
nder\sergey-2\war_story.blend"`

**Comment by RedRaptor93** [comment]
thank you, have you tried setting the output of your project to a folder? 

Try E:\project instead of the root E:\

**Comment by Baldassarre** [comment]
Hello,
the tool remain frozen in this way:
![cattura](https://cloud.githubusercontent.com/assets/26813284/24543317/787093ee-15ff-11e7-8ed3-4c01733ae5fe.JPG)

**Comment by lpslp** [comment]
tried change path to folder - same - freeze.
And is it matter - for me BRE freeze on same stage as Baldassarre indicate

**Comment by RedRaptor93** [comment]
@lpslp @Baldassarre I assume you guys are using the release version? Or have anyone tried compiling from the latest code?

I've made a release of our latest code, see if the freeze @Baldassarre showed still persists.

<a href="https://www.github.com/RedRaptor93/BlenderRenderController/releases">ver. 0.8.2-RC</a>

**Comment by lpslp** [comment]
we go here
https://github.com/RedRaptor93/BlenderRenderController
we see 
"Latest release HERE" and where we appear? 
here
https://github.com/jendabek/BlenderRenderController/releases/tag/0.8.0

but 0.8.2 do same - freeze
log
```
Сигнатура проблемы:
  Имя события проблемы:	APPCRASH
  Имя приложения:	blender.exe
  Версия приложения:	2.7.8.0
  Отметка времени приложения:	58dc674d
  Имя модуля с ошибкой:	MSVCR120.dll
  Версия модуля с ошибкой:	12.0.21005.1
  Отметка времени модуля с ошибкой:	524f83ff
  Код исключения:	40000015
  Смещение исключения:	0000000000074a46
  Версия ОС:	6.1.7601.2.1.0.256.1
  Код языка:	1049
  Дополнительные сведения 1:	8f27
  Дополнительные сведения 2:	8f273a46949532b247124c19dd9bfc51
  Дополнительные сведения 3:	16d8
  Дополнительные сведения 4:	16d8c41a357b60a7b47f8884a78d533f
```

**and appear new windows with new error :)**
![t3](https://cloud.githubusercontent.com/assets/19380636/24555916/115b8eaa-1633-11e7-913c-ab57ad20309d.jpg)

**Comment by Baldassarre** [comment]
Same thing...
![cattura](https://cloud.githubusercontent.com/assets/26813284/24556252/08fbea24-1634-11e7-92c9-3c6a81a73d2e.JPG)

**Comment by RedRaptor93** [comment]
me and @jendabek have been made alot of progress in the past month, guess he forgot to update the release 🙄 

that new error message means that `get_project_info` script failed to get info from the project.

does that happen when using _runWin7.bat_ ?

**Comment by Baldassarre** [comment]
Great! It seems to work now!
I come back when it finishes and I say you if it's ok :)
Thanks

**Comment by Baldassarre** [comment]
It works well (I hope for lpslp too), thanks beautiful job!

**Comment by jendabek** [comment]
So the running the program via runWin7.bat helped?
Sorry for the late replay, I have to work on other project too.

**Comment by Baldassarre** [comment]
Yes, it helped running the program via runWin7.bat.
