### ISSUE TITLE
Windows 10, audio out of sync

### ISSUE THREAD

**Issue by NuKA-J** [jendabek/BlenderRenderController#20]
The audio on the final render is out of sync, it starts out fine but the longer the render, the more out of sync it gets. 
The audio on individual chunks is perfectly fine.
Issue happens with both mixdown audio and without it. 
I have tried both codecs H.264 and xvid and same thing with both. H.264 is worse.

**Comment by RedRaptor93** [comment]
what video/audio settings your project's using?

**Comment by NuKA-J** [comment]
The Video settings I listed. the audio was AAC, 
however, with that said, I tried with MP3 for the audio, and now it works perfectly. so im starting to think this is more of a ffmpeg or codec issue.
