### ISSUE TITLE
BRC caught in loop rendering chunks forever...

### ISSUE THREAD

**Issue by axb2035** [jendabek/BlenderRenderController#22]
BRC v 0.8.0 running on Win 10.

BRC seems to be looping over the chunks (it says completed 11 of 4 chunks currently and seems to be continuing onwards...) and won't end (see image attached).

![image](https://cloud.githubusercontent.com/assets/3905694/25300715/2d82f3fc-2759-11e7-8099-f599f9da3749.png)

**Comment by RedRaptor93** [comment]
Hi, have you checked the output folder? Did any files get made?

Also, check the out [this](https://github.com/RedRaptor93/BlenderRenderController/releases/tag/0.8.2-RC) version, see if its any better.

**Comment by axb2035** [comment]
Is there a straight zip version to download rather than 7z? Thanks...

**Comment by RedRaptor93** [comment]
just drafted a new release, it should fix any hang issues

**Comment by Fred0211** [comment]
BRC still seems to be running in a loop for me. Can give specs if needed.

![1a](https://cloud.githubusercontent.com/assets/28388602/25699836/d05b8b86-30bc-11e7-8e2f-eb50a8b12227.png)
