### ISSUE TITLE
BRC stuck after chunks rendered

### ISSUE THREAD

**Issue by Fred0211** [jendabek/BlenderRenderController#24]
Render finished around 10 minute mark, never moves on to joining chunks/audio. Can give specs if needed. CPU stuck at 100% even though chunks are claimed to be rendered. If the render is stopped, all the chunks play except for last.

![1a](https://cloud.githubusercontent.com/assets/28388602/25700514/f4003b88-30bf-11e7-9492-602a254eb5e1.png)

**Comment by RedRaptor93** [comment]
Could you run the test again with "Detailed log" on and post the log file here?

Options -> Settings -> check  Detailed log box

**Comment by Fred0211** [comment]
Rendered everything again. If the log file is supposed to appear in the folder where BRC is, nothing appeared. The problem itself is to do with the number of frames i believe. This problem has only happened when the frames to render has been 17983. Making the number one frame higher or lower causes no issue.

**Comment by RedRaptor93** [comment]
That's bizarre... @jendabek look at this.

Also wierd that the log file did not appear, try moving it to another folder.

**Comment by Fred0211** [comment]
Moving it to another folder made the log file. Here is the log file, i hope this helps. Thanks

[log.txt](https://github.com/jendabek/BlenderRenderController/files/976827/log.txt)

**Comment by RedRaptor93** [comment]
Yep, confirmed, it hangs on the last chunk, for some reason it calls the last chunk to render over and over

`CEW: -b "E:\Bibliotecas E\_projetos\Blender\Video\teste\stuff\test_project.blend" -o "E:\Bibliotecas E\_projetos\Blender\Video\teste\asd\chunks\test_project-#" -E BLENDER_RENDER -s 15737 -e 17984 -a
1`

**Comment by jendabek** [comment]
Pedro, have you made any changes in the actual rendering process management?

**Comment by RedRaptor93** [comment]
no, but I found a fix, will push soon

**Comment by jendabek** [comment]
OK, will look at your push.

2017-05-04 23:01 GMT+02:00 Pedro Rodrigues <notifications@github.com>:

**Comment by RedRaptor93** [comment]
@jendabek 
https://github.com/jendabek/BlenderRenderController/commit/87641721066adece5e542752f43d87a587fad863

**Comment by RedRaptor93** [comment]
fixed in release [v0.8.2.1](https://github.com/jendabek/BlenderRenderController/releases/tag/0.8.2.1)
