### ISSUE TITLE
Script Folder is Missing.

### ISSUE THREAD

**Issue by Zyankali** [jendabek/BlenderRenderController#25]
hi there,

when I download the ZIP file from this source...

https://github.com/jendabek/BlenderRenderController/releases/download/v9.8.1/BRC_v981_Full-x64.zip

and open the program after extracting it´s loads fine. But when I would like to Open a Blend file it says that the
Script folder is missing.

Also there seems to be some errors with the json going on. Like The Start cant be Equal to the beginning. Well i checked my Blend file and all seems to be legit. Start and Endframe also that it´s uses absolute file paths.

I Wrote more detail excentantly on the issue board by Isti115 here. 

https://github.com/Isti115/BlenderRenderController/issues/12

there is also a Log file after I had installed manualy the Scripts folder from your Source.

But if I use that file from that source...

https://github.com/jendabek/BlenderRenderController/releases/download/0.8.2.1/BRC_0.8.2.1_Full-x64.zip

...

it works wunderfull.

**Comment by RedRaptor93** [comment]
I forgot to pack the scripts folder in the release 😒

The scripts have changed significantly since the older version.  You are using the latest scripts right? From here:

https://github.com/jendabek/BlenderRenderController/tree/master/Src/BRClib/Scripts

And they are in the same folder as the executable?

**Comment by Zyankali** [comment]
Yes i did and still the same problem.

**Comment by Zyankali** [comment]
Well i get some syntax errors when it loads up the get_project_info.py
Tells me that ther error is on line 7.

**Comment by Zyankali** [comment]
but interessting when i load up your new upped zip files all is ok.

**Comment by RedRaptor93** [comment]
All it's well then

The zips have the correct files now, my bad 😓
