### ISSUE TITLE
Silent error with old version of ffmpeg

### ISSUE THREAD

**Issue by tr00per** [jendabek/BlenderRenderController#27]
BRC failed silently and did not produce a joint video. I had an old version of ffmpeg, in which AAC codec was still in experimental phase. It's a default version of ffmpeg on Ubuntu 16.04 LTS, which required an additional argument passed to the tool (version 2.8.11-0ubuntu0.16.04.1).

```
The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
```

All went well after I updated ffmpeg manually to the latest version (3.3.4-static) and set a custom path to the tool, but it would be cool, if BRC detected the exit code of ffmpeg and not reported the processed finished successfully. Event better, if it could suggest updating to the latest version of the tool or even assert the minimum required version. AAC codec became official in version 3.0. Yes, it's "ancient", and so is Ubuntu 16.04 ;)

**Comment by RedRaptor93** [comment]
Nice find, I'll look into that.

I was also thinking of having more options related to the "after render" actions, like maybe allowing the user to define extra arguments, or letting them choose a files when

**Comment by RedRaptor93** [comment]
I downloaded the version you specified for windows, but it's working fine here.

By AAC you mean you set AAC as the AUDIO CODEC in Blender's Encoding panel, right? What other video settings did you use? (format, codec...)

**Comment by tr00per** [comment]
Format MPEG-4, codec H.264, audio codec AAC.

Search for "-strict" on this page, to see a short notice about this: https://trac.ffmpeg.org/wiki/Encode/AAC

**Comment by RedRaptor93** [comment]
I've added this to "Known issues".

Next time I have time I'll look into a solution for the next version release
