### ISSUE TITLE
BRC stalls at joining chunks stage...

### ISSUE THREAD

**Issue by axb2035** [jendabek/BlenderRenderController#29]
Kicked off job around 6:40am - chunk creation was completed about 7:20am. Audio track AOK. But joining chunks and adding sound is now stalled and has not progressed for over an hour.

First time using it on a new machine.
Windows 10; 32 GB RAM (no problems there); 101GB free on target drive (so should be OK).
Blender 2.79 - using new FFMPG settings (See image);
FFMPEG in PATH (confirmed by opening cmd and typing in ffmpeg - program executed as expected)
Audio is MP3 - so not the AAC error

At a loss for what to try next...

   - andrew

![image](https://user-images.githubusercontent.com/3905694/32419289-b92521f6-c2cb-11e7-8bd3-d66b36357aab.png)

![image](https://user-images.githubusercontent.com/3905694/32419236-12549564-c2cb-11e7-9333-941a0094cbd4.png)

**Comment by RedRaptor93** [comment]
You can start by getting the [latest version here](https://github.com/jendabek/BlenderRenderController/releases/latest)

One thing to note is that BRC doesn't really use PATH, it checks for the file directly at runtime (except on windows, where you can have a FFmpeg exe on the root folder and it'll use that), that might change in the future though.

The call to ffmpeg is what's acting up here, were the Chunks and the mixdown audio done successfully? They should be. In which case you can use the 'join chunks' option to manually.

If you can, try rendering a small part of that project and see if the problem persists.

**Comment by axb2035** [comment]
Thanks for the response... updated to new version and now it won't even render the chunks (see image) instead going straight to Completed, 0 frames rendered.

I think this is a different problem as this occurred after I replaced the .exe but used the old icon to run BRC from the taskbar. When I tried running from the directory where the .exe resides it worked fine. And copying ffmpeg to C: meant no problems with joining. So I think all is good...

Thank for you help and awesome addon!

![image](https://user-images.githubusercontent.com/3905694/32570667-f4743c84-c518-11e7-8548-624bf44f4099.png)

**Comment by RedRaptor93** [comment]
out of curiosity, did you replace just the EXE or all the package contents (dlls, the scripts folder...)? There were changes to those as well

**Comment by axb2035** [comment]
I completely replaced it all. I pinned it to the Taskbar and this morning when I tried to run it from the task bar it seem to break it again. I tried running from the folder where the .exe was installed and same problem. 

I uninstalled (i.e. deleted everything) and reinstalled again and ran from folder - all good again.

**Comment by RedRaptor93** [comment]
Errr... So it glitches out when you pin to the taskbar, AND it stays like that, even running from the exe later? 

That's weird 😕. Does this glitch state stays after a restart? This looks more a Windows issue TBH
