### ISSUE TITLE
Output renders only .Ac3

### ISSUE THREAD

**Issue by Medicraze** [jendabek/BlenderRenderController#30]
I've rendered multiple times before without issue. Tried different format with the same result. If i use "animation" for render in Blender VSE, it outputs fine. Just thought you should know.

After some trouble shooting, i noticed it was only rendering the audio. when only setting it to "join chunks" no file appears (yes i know where the output file is, and no there are no hidden files). 

Edit - (few hours later): noticed ffmpeg wasn't the most recent version. Updated to the 3.4 static window 64bit. Still no change in outcome.

Also, keep up the amazing work. You're a pretty amazing dude.

**Comment by RedRaptor93** [comment]
Thanks for the kind words 😄 

What render settings are you using? Format, Codec, Audio codec, etc. 

Does that problem happens on other projects?

**Comment by Medicraze** [comment]
Sorry for the delayed response. 
Here's an image link to my settings
https://ibb.co/kxhtAw

I also render 1080P 60fps. 

I'll give the render another sample to render. If I dont respond, it's because the bug is still there. :(

**Comment by Medicraze** [comment]
WELLLLLLLLLLLLP it works now....lol

Idk what the deal is because the settings have not changed since the bugged render. 

Keep up the great work. If you did some sneaky update, thanks lol
have a good one. I'll keep you posted, but if the program has logs, I can send them to you if you want them.

**Comment by RedRaptor93** [comment]
Haven't done any updates (unless you're compiling the source directly 📦 ) through one is coming soon

This new version will have improved logging, so make sure you have that version if this problem persists
