### ISSUE TITLE
global split job for long and small chunks for better load multi(many) core XEON CPU

### ISSUE THREAD

**Issue by lpslp** [jendabek/BlenderRenderController#32]
**suggestion**

it would be nice if script(BlenderRenderController) split video (job from blender) for work in two parts 90% (long chunks)+10%(short chunks) and render at first 90% long chunks and then second time split on threads remaining 10% (job from blender) FOR LOAD thread which already stand idle.
Explanation: now script(BlenderRenderController) split one time sequence at thread and if you are many threads with low Ghz per core last 1 or 2 parts in time take up to 15% of render time.

I for example have 2 cpu Xeon E5 2660V1 - 32 threads and if script will can split chunks in 90%-10% when threads end longs chunks they can take shots chunks and would not be idle while other threads render long pieces on the remaining threads which already stand idle. 
 
Now because I always wait in the end until the one remaining chunk end on ONE thread from 32 possible.

**Comment by red-rj** [comment]
If I understand correctly, you want a way for BRC to prioritize specific parts of the video?

**Comment by lpslp** [comment]
NO!
I want to BRC split video in for example 90/10 or 80/20 in % and when render of some parts from 90% or 80% (and ability to change this % amount)  chunk complete BRC will send SMALL parts from 10 or 20 % parts. because i did mention that when you have more cores, parts complete more randomly in time. Believe me when more users will have 16+core cpu this mention more people - half of chunsk render fast and other take longer but we can divide video in global parts and when threads from long (time) part idle we there throw smaler chunks....
for me this is one what BRC is missing in other sides, for me, it ideal. Back then some time ago I spent tens of times more on the same thing that now 
 BRC gives.
sorry for my english i translate by words straight from head. 
My first language is russian and if you accidentally russian too i can explain much much better. 
Thx for you effort
here some pic maybe it help http://i105.fastpic.ru/big/2018/0503/a5/04a71c05b87e24c042aea5973befbfa5.jpg

**Comment by lpslp** [comment]
Hi!
Writed video https://youtu.be/7Kf6wLfHE64 ilustration of what i writed some time ago - just take a look on distribuition load per core and carefully look at how take last 5 chucks time and then reread what i writed...i hope now you understand about what i talking about.
thx for your effort.

**Comment by lpslp** [comment]
sorry for i write all that, up. i am wery silly....
in BlenderRenderController from the beginning been functionality what i ask.

for those who like me, win many cores - just in punkt 3 chouse "custom" and change "Chunk Size" on low values like 150 or so.
